import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

// const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="h-screen w-full container-snap">
          <Navbar />
          <main className="min-h-screen py-8 mt-4 2xl:w-4/5 m-auto">
            {children}
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
